### ISSUE TITLE
How to use the buildpack

### ISSUE THREAD

**Issue by ghost** [nasali/oracle-oci8-heroku-buildpack#1]
We have an application that uses oracle, and trying to deploy on Heroku.  When I set BUILDPACK_URL to this repo, it errors:  Push rejected, no Cedar-supported app detected

**Comment by nasali** [comment]
Hi there,

I would need to see how you've configured your application and the full
stack trace of the failure when you push to Heroku to see what's up.

Thanks!

**Comment by ghost** [comment]
Hey thanks for the response, here is some backtrace:

```
  /tmp/build_4e07ecf33d22020ca8d11ee9775a0c15/vendor/ruby-2.1.2/bin/ruby extconf.rb
       checking for load library path...
       LD_LIBRARY_PATH...
       checking /vendor/instantclient_12_1... no
       checking ld.so.conf... no
       checking for cc... ok
       checking for gcc... yes
       checking for LP64... yes
       checking for sys/types.h... yes
       checking for ruby header... ok
       Get the version of Oracle from SQL*Plus... *** extconf.rb failed ***
       Could not create Makefile due to some reason, probably lack of necessary
       libraries and/or headers.  Check the mkmf.log file for more details.  You may
       need configuration options.

       Provided configuration options:
       --with-opt-dir
       --without-opt-dir
       --with-opt-include
       --without-opt-include=${opt-dir}/include
       --with-opt-lib
       --without-opt-lib=${opt-dir}/lib
       --with-make-prog
       --without-make-prog
       --srcdir=.
       --curdir
       --ruby=/tmp/build_4e07ecf33d22020ca8d11ee9775a0c15/vendor/ruby-2.1.2/bin/ruby
       --with-instant-client
       --without-instant-client
       /tmp/build_4e07ecf33d22020ca8d11ee9775a0c15/vendor/bundle/ruby/2.1.0/gems/ruby-oci8-2.1.7/ext/oci8/oraconf.rb:762:in `get_version': RuntimeError (RuntimeError)
       from /tmp/build_4e07ecf33d22020ca8d11ee9775a0c15/vendor/bundle/ruby/2.1.0/gems/ruby-oci8-2.1.7/ext/oci8/oraconf.rb:711:in `initialize'
       from /tmp/build_4e07ecf33d22020ca8d11ee9775a0c15/vendor/bundle/ruby/2.1.0/gems/ruby-oci8-2.1.7/ext/oci8/oraconf.rb:320:in `new'
       from /tmp/build_4e07ecf33d22020ca8d11ee9775a0c15/vendor/bundle/ruby/2.1.0/gems/ruby-oci8-2.1.7/ext/oci8/oraconf.rb:320:in `get'
       from extconf.rb:18:in `<main>'
       ---------------------------------------------------
       Error Message:
       cannot get Oracle version from sqlplus
       Backtrace:
       /tmp/build_4e07ecf33d22020ca8d11ee9775a0c15/vendor/bundle/ruby/2.1.0/gems/ruby-oci8-2.1.7/ext/oci8/oraconf.rb:762:in `get_version'
       /tmp/build_4e07ecf33d22020ca8d11ee9775a0c15/vendor/bundle/ruby/2.1.0/gems/ruby-oci8-2.1.7/ext/oci8/oraconf.rb:711:in `initialize'
       /tmp/build_4e07ecf33d22020ca8d11ee9775a0c15/vendor/bundle/ruby/2.1.0/gems/ruby-oci8-2.1.7/ext/oci8/oraconf.rb:320:in `new'
       /tmp/build_4e07ecf33d22020ca8d11ee9775a0c15/vendor/bundle/ruby/2.1.0/gems/ruby-oci8-2.1.7/ext/oci8/oraconf.rb:320:in `get'
       extconf.rb:18:in `<main>'

```

And here is my gemfile:

```
source 'https://rubygems.org'

ruby "2.1.2"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.0'
# Use sqlite3 as the database for Active Record
# gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

gem 'devise'

gem 'slim'

gem 'rails_12factor', group: :production

gem 'bootstrap-sass'
# bootstrap-sass-rails HH
# backed out of this
#gem "bootstrap-sass-rails", "~> 2.2.2.0"

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use oracle-enhanced BH
gem "activerecord-oracle_enhanced-adapter", "~> 1.5.0"

# Use debugger
# gem 'debugger', group: [:development, :test]

# Use oci8 BH
gem 'ruby-oci8'

# Fix Oracle BH
gem 'safe_attributes'

group :development do
    gem "rails-erd"
end
```

**Comment by nasali** [comment]
Okay, so it looks like the Oracle environment variable is not getting set
for the gem to install correctly. Since you only provided a snippet of the
Heroku push log, I'm going to guess that you do not have a trigger file for
this Buildpack to consume.

If such a trigger does not exist, please create an empty file and name it
".oracle.ini" without the double quotes and place it in the root folder of
your Rails application. Then, add it to your repo, commit it, and try a new
push again to Heroku.

If that fails, it'd be very helpful to see the results of the Heroku push
in their entirety.

Thanks!

**Comment by pablogravielseo** [comment]
Im using this buildpack and have the same issue, have a solution? 

Error Message:
Set the environment variable ORACLE_HOME if Oracle Full Client.
Append the path of Oracle client libraries to LD_LIBRARY_PATH if Oracle Instant Client.
